 version: '3'
 services:
   bot-validation-assistant:
     restart: always
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     volumes:
       - .:/code
     ports:
       - "8000:8000"
     depends_on:
      - db
   db:
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
